version: 2.1
orbs:
  python: circleci/python@1.4.0
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
         name: Prepare environment
         command: |
           python3 -m venv venv
           . venv/bin/activate
           pip install -r requirements.txt
      - run:
         name: Verify PEP8
         command: |
           . venv/bin/activate
           flake8 --ignore=E501 carsblog/carsblog/settings.py carsblog
workflows:
  sample:
    jobs:
      - build-and-test
